### ISSUE TITLE
横向滚动超过超过一定数量后会有错误

### ISSUE THREAD

**Issue by 5653325** [ciaoca/cxScroll#3]
如：li的width为280px，li里面包含一个img，width是270px.一共是50个li，在滚动到第39个以后，图片就不会在有滚动效果了（后面就是空白了）。
**修正方法，是把list样式中的width:9999px修改大一些，比如99999px**
![qq 20180711092203](https://user-images.githubusercontent.com/3361135/42545669-e7b91116-84eb-11e8-8bf3-a25c3b23c415.png)

**Comment by ciaoca** [comment]
恭喜你找到的了正确的解决方法
